### ISSUE TITLE
Projet similaire

### ISSUE THREAD

**Issue by Tchoupinax** [HachemiH/javascript-tutorial-fr#1]
Salut,

L'auteur EN m'a montré ton projet, j'ai aussi débuté la traduction [ici](https://github.com/Tchoupinax/javascript-tutorial-fr).

On s'organise comment ? :)

**Comment by HachemiH** [comment]
Salut,

Là j'ai tout traduit jusqu'aux boucles, je me suis fixé comme deadline (un peu optimiste) d'avoir traduit la plus grande partie pour la fin du mois.

Je m'efforce d'être le plus fidèle possible de l'original.
Je te propose d'en discuter de vive voix, on sera plus efficace que par écrit.
